### ISSUE TITLE
chain-registry: update chain.json to 0.8.0

### ISSUE THREAD

**Issue by andy108369** [elys-network/elys#143]
someone needs to bump the version 0.4.0 to 0.8.0 here https://github.com/cosmos/chain-registry/blob/11f0b018eed478e4b238ac3e0aafc672df53a67c/testnets/elystestnet/chain.json

FWIW, I'm currently using this chain.json => https://gist.githubusercontent.com/andy108369/727bb9d8612fc66e9db35eebf183afe3/raw/51b703b3f895a2ec5e492dbc3ae8d7bf2a0c19d2/elys-chain.json

cc @cosmic-vagabond 

refs
https://github.com/elys-network/elys/issues/39#issuecomment-1557259870

**Comment by cosmic-vagabond** [comment]
good call out @andy108369 I created this PR to update to the latest version as well as include the previous versions that were not added yet https://github.com/cosmos/chain-registry/pull/2498
