### ISSUE TITLE
chain-registry: update chain.json to 0.12.0

### ISSUE THREAD

**Issue by arno01** [elys-network/elys#204]
similarly to https://github.com/elys-network/elys/issues/143 , please update https://github.com/cosmos/chain-registry/blob/master/testnets/elystestnet/chain.json

**Comment by arno01** [comment]
cc @cosmic-vagabond

**Comment by cosmic-vagabond** [comment]
@arno01 thanks for pointing that one out, I created a PR with the latest version of the elys binary info here: https://github.com/cosmos/chain-registry/pull/2957
