### ISSUE TITLE
Error validator node 

### ISSUE THREAD

**Issue by Enigma-Validator** [elys-network/elys#318]
Our validator node stoped.

We are using docker in order to launch and maintain our validator node, we upgraded yesterday and our node stoped this morning with some logs; We upgraded go but don't seems to be the issu

`
elys-testnets_chain  | 11:07AM INF Vesting tokens for vestingInfo module=x/commitment
elys-testnets_chain  | thread '<unnamed>' panicked at 'There is an old error message in the given pointer that has not been cleaned up. Error message pointers should not be reused for multiple calls.', src/error/rust.rs:132:13
elys-testnets_chain  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
elys-testnets_chain  | fatal runtime error: failed to initiate panic, error 5
elys-testnets_chain  | SIGABRT: abort
elys-testnets_chain  | PC=0x7fef9a06e9fc m=8 sigcode=18446744073709551610
elys-testnets_chain  | signal arrived during cgo execution
elys-testnets_chain  | 
elys-testnets_chain  | goroutine 10 [syscall]:
elys-testnets_chain  | runtime.cgocall(0x23e16c0, 0xc006aef1e0)
elys-testnets_chain  |  /usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc006aef1b8 sp=0xc006aef180 pc=0x40b0eb
elys-testnets_chain  | github.com/CosmWasm/wasmvm/internal/api._C2func_execute(0x7fef1000e940, {0x0, 0xc006a680a0, 0x20}, {0x0, 0xc0008c16c0, 0xc7}, {0x0, 0xc00014af20, 0xa8}, ...)
elys-testnets_chain  |  _cgo_gotypes.go:304 +0x71 fp=0xc006aef1e0 sp=0xc006aef1b8 pc=0x14aab11
elys-testnets_chain  | github.com/CosmWasm/wasmvm/internal/api.Execute.func1({0x10?}, {0x1?, 0xc006a680a0?, 0xffff?}, {0x99?, 0xc0008c16c0?, 0x25c7860?}, {0x0, 0xc00014af20, 0xa8}, ...)
elys-testnets_chain  |  /root/go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.3.0/internal/api/lib.go:235 +0x238 fp=0xc006aef370 sp=0xc006aef1e0 pc=0x14b3298
elys-testnets_chain  | github.com/CosmWasm/wasmvm/internal/api.Execute({0x392e338?}, {0xc006a680a0?, 0x0?, 0xc006aef748?}, {0xc0008c16c0?, 0xc006a665c0?, 0x20?}, {0xc00014af20, 0xa8, 0xb0}, ...)
elys-testnets_chain  |  /root/go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.3.0/internal/api/lib.go:235 +0x6a7 fp=0xc006aef670 sp=0xc006aef370 pc=0x14b2d07
elys-testnets_chain  | github.com/CosmWasm/wasmvm.(*VM).Execute(0xc002c83ed0, {0xc006a680a0, 0x20, 0x20}, {{0x470f38, 0x17a30c5532c917f1, {0xc0060f4490, 0xd}}, 0xc006a0d598, {{0xc006921c40, ...}}}, ...)
elys-testnets_chain  |  /root/go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.3.0/lib.go:187 +0x276 fp=0xc006aef790 sp=0xc006aef670 pc=0x14bc616
elys-testnets_chain  | github.com/CosmWasm/wasmd/x/wasm/keeper.Keeper.execute({{0x3943950, 0xc0018017b0}, {0x398a598, 0xc001b59a60}, {0x39488f0, 0xc001809360}, {0x393ab20, 0xc002c83e90}, {0x39386c0, 0xc0006550c0}, ...}, ...)
elys-testnets_chain  |  /root/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.41.0/x/wasm/keeper/keeper.go:386 +0xba2 fp=0xc006af1248 sp=0xc006aef790 pc=0x1e2b082
elys-testnets_chain  | github.com/CosmWasm/wasmd/x/wasm/keeper.msgServer.ExecuteContract({0x41203a?}, {0x3968808, 0xc006a41d40}, 0xc0069f2780)
elys-testnets_chain  |  /root/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.41.0/x/wasm/keeper/msg_server.go:127 +0x1eb fp=0xc006af1a60 sp=0xc006af1248 pc=0x1e3d3cb
elys-testnets_chain  | github.com/CosmWasm/wasmd/x/wasm/keeper.(*msgServer).ExecuteContract(0x411b05?, {0x3968808?, 0xc006a41d40?}, 0x29d35c0?)
elys-testnets_chain  |  <autogenerated>:1 +0x2e fp=0xc006af1a90 sp=0xc006af1a60 pc=0x1e5af4e
elys-testnets_chain  | github.com/CosmWasm/wasmd/x/wasm/types._Msg_ExecuteContract_Handler.func1({0x3968808, 0xc006a41d40}, {0x295f6c0?, 0xc0069f2780})
elys-testnets_chain  |  /root/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.41.0/x/wasm/types/tx.pb.go:2012 +0x72 fp=0xc006af1ad0 sp=0xc006af1a90 pc=0x1522312
elys-testnets_chain  | github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x39683a8, 0xc006a26580}, {0xc006af1b68?, 0x411b05?}, 0x2a0?, 0xc006913aa0)
elys-testnets_chain  |  /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.47.4/baseapp/msg_service_router.go:118 +0x93 fp=0xc006af1b20 sp=0xc006af1ad0 pc=0x116c373
elys-testnets_chain  | github.com/CosmWasm/wasmd/x/wasm/types._Msg_ExecuteContract_Handler({0x28d9160?, 0xc0001869f0}, {0x39683a8, 0xc006a26580}, 0x33e54e0, 0xc006957fa0)
elys-testnets_chain  |  /root/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.41.0/x/wasm/types/tx.pb.go:2014 +0x135 fp=0xc006af1b78 sp=0xc006af1b20 pc=0x15221f5
`

**Comment by cosmic-vagabond** [comment]
@Enigma-Validator could you share the steps to reproduce the issue

**Comment by cosmic-vagabond** [comment]
@Enigma-Validator, this issue is being closed due to inactivity over the past few weeks. However, should the problem persist, please don't hesitate to reopen it.
