### ISSUE TITLE
new tag needed (binary name)

### ISSUE THREAD

**Issue by andy108369** [elys-network/elys#38]
Can you guys tag https://github.com/elys-network/elys/commit/25d7b00b7a81fed3c5373db5bd240fd0692468e3 with 0.2.3 or 0.2.4?
I'd like to add Elys to https://github.com/akash-network/cosmos-omnibus but the build break without that commit due to `/go/bin/main` vs `/go/bin/elysd` :-)

As a quick workaround I've just [added](https://github.com/akash-network/cosmos-omnibus/pull/452/commits/bc9b8ea27592951b2a55b506c2632288a4e399b0) a check and  `main` -> `elysd` rename operation.

**Comment by cosmic-vagabond** [comment]
Big thanks to @andy108369 for hooking us up with this integration! We just released version `v0.3.0` on https://github.com/elys-network/elys/releases/tag/v0.3.0 with all the changes you made. Thanks again.
