### ISSUE TITLE
panic: Int overflow in PowApprox in x/amm/types/pow_approx.go

### ISSUE THREAD

**Issue by avkr003** [elys-network/elys#669]
To replicate this issue, use the following values:

`powPrecision := sdk.MustNewDecFromStr("0.00000001")`
`base := sdk.MustNewDecFromStr("10004.000000000024712350")`
`exp := sdk.MustNewDecFromStr("0.0002")`
`value := types.PowApprox(base, exp, powPrecision)`

Here, the `powPrecision` value is the same as in the `amm` module.

**Comment by avkr003** [comment]
Added [PR 671](https://github.com/elys-network/elys/pull/671) to close this

**Comment by amityadav0** [comment]
PR #671 is merged
